# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: trang.mtht020316@gmail.com
author_name: Lin
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_apod
project_short_description: A JupyterLab extension.
python_name: jupyterlab_apod
repository: ''
test: true

